-- =====================================================================
-- MIGRAÇÃO V2 - OFICINA MECÂNICA
-- Adiciona suporte a múltiplos serviços por agendamento (orçamento).
-- Execute este script no SQL Editor do Supabase (projeto já existente).
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. Nova tabela: agendamento_servicos
-- Cada linha representa um item (serviço) dentro de um agendamento.
-- O preço é "congelado" no momento da adição (preco_unitario), para que
-- alterações futuras na tabela `servicos` não mudem orçamentos antigos.
-- ---------------------------------------------------------------------
create table if not exists public.agendamento_servicos (
  id bigint generated by default as identity primary key,
  agendamento_id bigint not null references public.agendamentos(id) on delete cascade,
  servico_id bigint not null references public.servicos(id) on delete restrict,
  quantidade integer not null default 1 check (quantidade > 0),
  preco_unitario decimal(10,2) not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_agendamento_servicos_agendamento_id
  on public.agendamento_servicos(agendamento_id);

alter table public.agendamento_servicos enable row level security;

drop policy if exists "agendamento_servicos_select_publica" on public.agendamento_servicos;
create policy "agendamento_servicos_select_publica" on public.agendamento_servicos for select using (true);

drop policy if exists "agendamento_servicos_insert_publica" on public.agendamento_servicos;
create policy "agendamento_servicos_insert_publica" on public.agendamento_servicos for insert with check (true);

drop policy if exists "agendamento_servicos_update_publica" on public.agendamento_servicos;
create policy "agendamento_servicos_update_publica" on public.agendamento_servicos for update using (true) with check (true);

drop policy if exists "agendamento_servicos_delete_publica" on public.agendamento_servicos;
create policy "agendamento_servicos_delete_publica" on public.agendamento_servicos for delete using (true);

-- ---------------------------------------------------------------------
-- 2. Migra agendamentos antigos (com servico_id único) para a nova tabela
-- Isso preserva os dados de teste que você já cadastrou.
-- ---------------------------------------------------------------------
insert into public.agendamento_servicos (agendamento_id, servico_id, quantidade, preco_unitario)
select a.id, a.servico_id, 1, coalesce(s.preco, 0)
from public.agendamentos a
join public.servicos s on s.id = a.servico_id
where a.servico_id is not null
  and not exists (
    select 1 from public.agendamento_servicos ags where ags.agendamento_id = a.id
  );

-- ---------------------------------------------------------------------
-- 3. Remove a coluna antiga servico_id de agendamentos
-- (agora cada agendamento pode ter vários serviços, via agendamento_servicos)
-- ---------------------------------------------------------------------
alter table public.agendamentos drop column if exists servico_id;

-- =====================================================================
-- FIM DA MIGRAÇÃO
-- =====================================================================
