-- =====================================================================
-- SISTEMA OFICINA MECÂNICA - SCRIPT DE CRIAÇÃO DO BANCO (SUPABASE)
-- Execute este script inteiro no SQL Editor do seu projeto Supabase.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. TABELA: clientes
-- ---------------------------------------------------------------------
create table if not exists public.clientes (
  id bigint generated by default as identity primary key,
  nome text not null,
  telefone text,
  cpf text,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- 2. TABELA: veiculos
-- ---------------------------------------------------------------------
create table if not exists public.veiculos (
  id bigint generated by default as identity primary key,
  cliente_id bigint not null references public.clientes(id) on delete cascade,
  marca text not null,
  modelo text not null,
  placa text not null unique,
  ano integer,
  created_at timestamptz not null default now()
);

create index if not exists idx_veiculos_cliente_id on public.veiculos(cliente_id);

-- ---------------------------------------------------------------------
-- 3. TABELA: servicos
-- ---------------------------------------------------------------------
create table if not exists public.servicos (
  id bigint generated by default as identity primary key,
  descricao text not null,
  preco decimal(10,2) not null default 0,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- 4. TABELA: agendamentos
-- ---------------------------------------------------------------------
create table if not exists public.agendamentos (
  id bigint generated by default as identity primary key,
  cliente_id bigint not null references public.clientes(id) on delete cascade,
  veiculo_id bigint not null references public.veiculos(id) on delete cascade,
  servico_id bigint not null references public.servicos(id) on delete restrict,
  data_hora timestamptz not null,
  status text not null default 'Pendente'
    check (status in ('Pendente', 'Em Andamento', 'Concluído', 'Cancelado')),
  observacoes text,
  created_at timestamptz not null default now()
);

create index if not exists idx_agendamentos_cliente_id on public.agendamentos(cliente_id);
create index if not exists idx_agendamentos_veiculo_id on public.agendamentos(veiculo_id);
create index if not exists idx_agendamentos_data_hora on public.agendamentos(data_hora);

-- =====================================================================
-- 5. ROW LEVEL SECURITY (RLS)
-- Habilita RLS e cria políticas públicas (leitura/escrita liberadas)
-- para permitir o funcionamento do app usando apenas a "anon key".
--
-- ATENÇÃO: isso deixa o banco aberto para qualquer pessoa que tenha a
-- anon key (que fica visível no frontend). É adequado para uso interno
-- rápido/protótipo. Para produção real, considere ativar o Supabase
-- Auth e restringir as políticas por usuário autenticado.
-- =====================================================================

alter table public.clientes enable row level security;
alter table public.veiculos enable row level security;
alter table public.servicos enable row level security;
alter table public.agendamentos enable row level security;

-- CLIENTES
drop policy if exists "clientes_select_publica" on public.clientes;
create policy "clientes_select_publica" on public.clientes for select using (true);

drop policy if exists "clientes_insert_publica" on public.clientes;
create policy "clientes_insert_publica" on public.clientes for insert with check (true);

drop policy if exists "clientes_update_publica" on public.clientes;
create policy "clientes_update_publica" on public.clientes for update using (true) with check (true);

drop policy if exists "clientes_delete_publica" on public.clientes;
create policy "clientes_delete_publica" on public.clientes for delete using (true);

-- VEICULOS
drop policy if exists "veiculos_select_publica" on public.veiculos;
create policy "veiculos_select_publica" on public.veiculos for select using (true);

drop policy if exists "veiculos_insert_publica" on public.veiculos;
create policy "veiculos_insert_publica" on public.veiculos for insert with check (true);

drop policy if exists "veiculos_update_publica" on public.veiculos;
create policy "veiculos_update_publica" on public.veiculos for update using (true) with check (true);

drop policy if exists "veiculos_delete_publica" on public.veiculos;
create policy "veiculos_delete_publica" on public.veiculos for delete using (true);

-- SERVICOS
drop policy if exists "servicos_select_publica" on public.servicos;
create policy "servicos_select_publica" on public.servicos for select using (true);

drop policy if exists "servicos_insert_publica" on public.servicos;
create policy "servicos_insert_publica" on public.servicos for insert with check (true);

drop policy if exists "servicos_update_publica" on public.servicos;
create policy "servicos_update_publica" on public.servicos for update using (true) with check (true);

drop policy if exists "servicos_delete_publica" on public.servicos;
create policy "servicos_delete_publica" on public.servicos for delete using (true);

-- AGENDAMENTOS
drop policy if exists "agendamentos_select_publica" on public.agendamentos;
create policy "agendamentos_select_publica" on public.agendamentos for select using (true);

drop policy if exists "agendamentos_insert_publica" on public.agendamentos;
create policy "agendamentos_insert_publica" on public.agendamentos for insert with check (true);

drop policy if exists "agendamentos_update_publica" on public.agendamentos;
create policy "agendamentos_update_publica" on public.agendamentos for update using (true) with check (true);

drop policy if exists "agendamentos_delete_publica" on public.agendamentos;
create policy "agendamentos_delete_publica" on public.agendamentos for delete using (true);

-- =====================================================================
-- FIM DO SCRIPT
-- =====================================================================
